name: Build Extension
on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        run: |
          cd build
          npm install
          npm run build-ci
        shell: bash

      - name: Prepare artifacts
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir artifacts
          cp dist/*.vsix artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: matrix.os == 'ubuntu-latest'
        with:
          name: ql-for-vscode-extension
          path: artifacts
